#!/usr/bin/env bash
# FDE Forge AI — one-command setup + start
#
# TCS Mac (no Docker, no Homebrew required):
#   Uses already-installed npm/Node, Python, and Postgres.
#   Redis/MinIO: use if on PATH; otherwise warn and continue.
#   AI: Bedrock via existing ~/.aws
#
# AWS EC2 (Docker):
#   docker compose up --build -d --scale worker=N
#
# Usage (from repo root fde-forge-ai/):
#   chmod +x setup.sh scripts/stop.sh
#   FORCE_MODE=native ./setup.sh
#
# Optional:
#   FORCE_MODE=native|docker ./setup.sh
#   WORKER_REPLICAS=4 ./setup.sh     # EC2 Celery scale (default 2)
#   SKIP_START=1 ./setup.sh          # install deps only
#   PGHOST / PGPORT / PGUSER         # override Postgres connection for role/db setup
#   ./scripts/stop.sh                # stop native processes

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

RUN_DIR="$ROOT/.run"
LOG_DIR="$RUN_DIR/logs"
PID_DIR="$RUN_DIR/pids"
BIN_DIR="$RUN_DIR/bin"
NATIVE_ENV="$ROOT/.env.native"
COMPOSE_ENV="$ROOT/.env"

mkdir -p "$LOG_DIR" "$PID_DIR" "$BIN_DIR"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${BLUE}==>${NC} $*"; }
ok()   { echo -e "${GREEN}✔${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }
die()  { echo -e "${RED}✖${NC} $*"; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

HAS_BREW=0
if have brew; then
  HAS_BREW=1
fi

detect_mode() {
  if [[ "${FORCE_MODE:-}" == "native" || "${FORCE_MODE:-}" == "docker" ]]; then
    echo "$FORCE_MODE"
    return
  fi
  if have docker && docker info >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    echo "docker"
  else
    echo "native"
  fi
}

wait_http() {
  local url="$1" name="$2" tries="${3:-60}"
  local i=0
  while (( i < tries )); do
    if curl -sf "$url" >/dev/null 2>&1; then
      ok "$name is up ($url)"
      return 0
    fi
    sleep 1
    ((i++)) || true
  done
  warn "$name not responding yet at $url (check $LOG_DIR)"
  return 1
}

optional_brew_install() {
  local pkg="$1"
  if (( HAS_BREW == 0 )); then
    return 1
  fi
  if brew list --versions "$pkg" >/dev/null 2>&1 || brew list --cask --versions "$pkg" >/dev/null 2>&1; then
    ok "$pkg already installed (brew)"
    return 0
  fi
  log "Installing $pkg via Homebrew (optional)..."
  brew install "$pkg"
}

write_native_env() {
  # Keep existing native .env so secret keys don't rotate on every re-run
  if [[ -f "$COMPOSE_ENV" ]] && grep -q '127.0.0.1:5432/fde_forge' "$COMPOSE_ENV" 2>/dev/null \
    && grep -q '^BEDROCK_ENABLED=true' "$COMPOSE_ENV" 2>/dev/null; then
    ok "Using existing .env (native + Bedrock)"
    return
  fi

  log "Writing native .env (localhost services + Bedrock only)..."
  local secret csrf existing_openai=""
  if [[ -f "$COMPOSE_ENV" ]]; then
    secret="$(grep -E '^SECRET_KEY=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- || true)"
    csrf="$(grep -E '^CSRF_SECRET=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- || true)"
    existing_openai="$(grep -E '^OPENAI_API_KEY=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- || true)"
  fi
  [[ -n "${secret:-}" ]] || secret="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"
  [[ -n "${csrf:-}" ]] || csrf="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"

  # Allow company Postgres credentials via env overrides
  local db_user="${FDE_DB_USER:-fde}"
  local db_pass="${FDE_DB_PASSWORD:-fde_secret}"
  local db_name="${FDE_DB_NAME:-fde_forge}"
  local db_host="${FDE_DB_HOST:-127.0.0.1}"
  local db_port="${FDE_DB_PORT:-5432}"

  cat > "$NATIVE_ENV" <<EOF
# Auto-generated by setup.sh for TCS Mac (native / no Docker / no Homebrew required)
# AI: Bedrock only — uses ~/.aws (already configured on TCS)
APP_ENV=development
APP_NAME=FDE Forge AI
APP_TAGLINE=Transform AI Engineers into Customer-Ready Forward Deployed Engineers.
APP_URL=http://localhost:5173
API_URL=http://localhost:8000
API_PREFIX=/api/v1
SECRET_KEY=${secret}
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
CSRF_SECRET=${csrf}
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
COOKIE_SECURE=false
COOKIE_SAMESITE=lax

DATABASE_URL=postgresql+asyncpg://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}
DATABASE_URL_SYNC=postgresql://${db_user}:${db_pass}@${db_host}:${db_port}/${db_name}

REDIS_URL=redis://127.0.0.1:6379/0
CELERY_BROKER_URL=redis://127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/1

S3_ENDPOINT=http://127.0.0.1:9000
S3_PUBLIC_ENDPOINT=http://127.0.0.1:9000
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=minioadmin
S3_BUCKET=fde-forge
S3_REGION=us-east-1
S3_USE_SSL=false

OPENAI_API_KEY=${existing_openai}
OPENAI_MODEL=gpt-4o-mini
OPENAI_EMBEDDING_MODEL=text-embedding-3-small
AI_DEFAULT_PROVIDER=bedrock
DEFAULT_LLM_PROVIDER=bedrock
ENABLED_LLM_PROVIDERS=bedrock
AI_DEFAULT_MODEL=gpt-4o-mini
AI_MAX_RETRIES=3
AI_REQUEST_TIMEOUT_SECONDS=180
AI_DAILY_ORG_BUDGET=50.00
AI_FALLBACK_MODEL=

BEDROCK_ENABLED=true
AWS_REGION=us-east-1
BEDROCK_MODEL_ID=us.anthropic.claude-sonnet-4-5-20250929-v1:0
BEDROCK_EMBEDDING_MODEL_ID=amazon.titan-embed-text-v2:0
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

SMTP_HOST=127.0.0.1
SMTP_PORT=1025
SMTP_FROM_EMAIL=noreply@fdeforge.example.com
SMTP_USE_TLS=false

LOG_LEVEL=INFO
SEED_ADMIN_EMAIL=saurabh@fdeforge.example.com
SEED_ADMIN_PASSWORD=admin123
SEED_LEARNER_PASSWORD=ChangeMeLearner123!
EOF

  cp "$NATIVE_ENV" "$COMPOSE_ENV"
  ok "Wrote $COMPOSE_ENV (Bedrock only for TCS Mac)"
}

setup_postgres_native() {
  have psql || die "psql not found. Postgres client tools required (no Homebrew). Ask IT or use company Postgres."
  have createdb || warn "createdb not on PATH — will try CREATE DATABASE via psql"

  # If brew Postgres exists, prefer it — but never required
  if (( HAS_BREW == 1 )); then
    local pg_prefix
    pg_prefix="$(brew --prefix postgresql@16 2>/dev/null || brew --prefix postgresql 2>/dev/null || true)"
    if [[ -n "${pg_prefix:-}" && -d "$pg_prefix/bin" ]]; then
      export PATH="$pg_prefix/bin:$PATH"
    fi
    if brew services list 2>/dev/null | grep -Eq "postgresql(@[0-9]+)?.*started"; then
      ok "Postgres brew service already running"
    elif brew list --versions postgresql@16 >/dev/null 2>&1; then
      brew services start postgresql@16 2>/dev/null || true
    fi
  fi

  local db_user="${FDE_DB_USER:-fde}"
  local db_pass="${FDE_DB_PASSWORD:-fde_secret}"
  local db_name="${FDE_DB_NAME:-fde_forge}"
  local db_host="${FDE_DB_HOST:-127.0.0.1}"
  local db_port="${FDE_DB_PORT:-5432}"

  # Probe: either local socket as current OS user, or TCP with admin
  log "Ensuring Postgres role/db (${db_user}@${db_host}:${db_port}/${db_name})..."

  if ! PGPASSWORD="$db_pass" psql -h "$db_host" -p "$db_port" -U "$db_user" -d "$db_name" -c 'SELECT 1' >/dev/null 2>&1; then
    # Try as current user / postgres superuser without password (common on Mac company images)
    if psql -h "$db_host" -p "$db_port" -d postgres -tAc "SELECT 1" >/dev/null 2>&1; then
      psql -h "$db_host" -p "$db_port" -d postgres -v ON_ERROR_STOP=1 <<SQL || true
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${db_user}') THEN
    CREATE ROLE ${db_user} LOGIN PASSWORD '${db_pass}' SUPERUSER;
  ELSE
    ALTER ROLE ${db_user} WITH LOGIN PASSWORD '${db_pass}';
  END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${db_name} OWNER ${db_user}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${db_name}')\gexec
SQL
    elif psql -d postgres -tAc "SELECT 1" >/dev/null 2>&1; then
      psql -d postgres -v ON_ERROR_STOP=1 <<SQL || true
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${db_user}') THEN
    CREATE ROLE ${db_user} LOGIN PASSWORD '${db_pass}' SUPERUSER;
  ELSE
    ALTER ROLE ${db_user} WITH LOGIN PASSWORD '${db_pass}';
  END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${db_name} OWNER ${db_user}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${db_name}')\gexec
SQL
    else
      die "Cannot connect to Postgres. Start company Postgres or set FDE_DB_HOST/USER/PASSWORD."
    fi
  fi

  PGPASSWORD="$db_pass" psql -h "$db_host" -p "$db_port" -U "$db_user" -d "$db_name" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' >/dev/null
  PGPASSWORD="$db_pass" psql -h "$db_host" -p "$db_port" -U "$db_user" -d "$db_name" -c 'CREATE EXTENSION IF NOT EXISTS vector;' >/dev/null 2>&1 \
    || warn "vector extension failed — install pgvector for your Postgres if RAG features need it"
  PGPASSWORD="$db_pass" psql -h "$db_host" -p "$db_port" -U "$db_user" -d "$db_name" -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' >/dev/null
  ok "Postgres ready (${db_name} @ ${db_host}:${db_port})"
}

setup_redis_native() {
  if have redis-cli && redis-cli ping >/dev/null 2>&1; then
    ok "Redis already running (6379)"
    return
  fi

  if have redis-server; then
    log "Starting redis-server..."
    nohup redis-server --daemonize no --port 6379 >"$LOG_DIR/redis.log" 2>&1 &
    echo $! >"$PID_DIR/redis.pid"
    sleep 1
    if redis-cli ping >/dev/null 2>&1; then
      ok "Redis started"
      return
    fi
  fi

  if (( HAS_BREW == 1 )); then
    optional_brew_install redis || true
    brew services start redis 2>/dev/null || true
    sleep 1
    if redis-cli ping >/dev/null 2>&1; then
      ok "Redis ready via Homebrew"
      return
    fi
  fi

  warn "Redis not found/running — Celery/background jobs (resume extract) will fail until Redis is available."
  warn "App API + Web will still start. Install redis-server on PATH or start company Redis on :6379."
}

setup_minio_native() {
  if curl -sf "http://127.0.0.1:9000/minio/health/live" >/dev/null 2>&1; then
    ok "MinIO already running (:9000)"
    return
  fi

  if ! have minio; then
    if (( HAS_BREW == 1 )); then
      brew install minio/stable/minio 2>/dev/null || brew install minio 2>/dev/null || true
    fi
  fi

  if ! have minio; then
    warn "MinIO not on PATH — resume/file uploads need object storage on :9000."
    warn "API + Web will still start. Install minio binary or point S3_* in .env to AWS S3."
    return
  fi

  mkdir -p "$RUN_DIR/minio-data"
  log "Starting MinIO..."
  nohup env MINIO_ROOT_USER=minioadmin MINIO_ROOT_PASSWORD=minioadmin \
    minio server "$RUN_DIR/minio-data" --address ":9000" --console-address ":9001" \
    >"$LOG_DIR/minio.log" 2>&1 &
  echo $! >"$PID_DIR/minio.pid"
  sleep 2

  if have mc; then
    mc alias set local http://127.0.0.1:9000 minioadmin minioadmin >/dev/null 2>&1 || true
    mc mb -p local/fde-forge >/dev/null 2>&1 || true
  elif have aws; then
    AWS_ACCESS_KEY_ID=minioadmin AWS_SECRET_ACCESS_KEY=minioadmin \
      aws --endpoint-url http://127.0.0.1:9000 s3 mb s3://fde-forge >/dev/null 2>&1 || true
  fi
  ok "MinIO ready (http://127.0.0.1:9000)"
}

setup_python_native() {
  local py=""
  if have python3.12; then
    py="$(command -v python3.12)"
  elif have python3; then
    py="$(command -v python3)"
  else
    die "Python 3 not found. Install company Python 3.12+ (no Homebrew)."
  fi

  local ver
  ver="$("$py" -c 'import sys; print("%d.%d"%sys.version_info[:2])')"
  log "Python: $($py --version) ($py)"
  "$py" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' \
    || die "Python 3.11+ required (found $ver)"

  if [[ ! -d "$ROOT/apps/api/.venv" ]]; then
    "$py" -m venv "$ROOT/apps/api/.venv" || die "python -m venv failed"
  fi
  # shellcheck disable=SC1091
  source "$ROOT/apps/api/.venv/bin/activate"
  pip install -q --upgrade pip
  log "Installing API package into venv..."
  pip install -q -e "$ROOT/apps/api[dev]"
  ok "Python venv ready"
}

setup_node_native() {
  have node || die "Node.js not found (required). npm alone is not enough — need node on PATH."
  have npm || die "npm not found. Node/npm must be installed (you said npm is installed — check PATH)."

  log "Node: $(node --version) / npm $(npm --version)"
  log "Installing web dependencies with npm..."
  (cd "$ROOT/apps/web" && npm install)
  ok "Web dependencies ready (npm)"
}

migrate_and_seed_native() {
  # shellcheck disable=SC1091
  source "$ROOT/apps/api/.venv/bin/activate"
  export PYTHONPATH="$ROOT/apps/api:$ROOT:${PYTHONPATH:-}"
  set -a
  # shellcheck disable=SC1090
  source "$COMPOSE_ENV"
  set +a

  log "Running Alembic migrations..."
  (cd "$ROOT/apps/api" && alembic -c alembic.ini upgrade head)
  log "Seeding demo data..."
  (cd "$ROOT" && PYTHONPATH="$ROOT/apps/api:$ROOT" python -m scripts.seed) || warn "Seed had warnings (often OK if already seeded)"
  ok "DB migrated + seeded"
}

start_api_native() {
  if [[ -f "$PID_DIR/api.pid" ]] && kill -0 "$(cat "$PID_DIR/api.pid")" 2>/dev/null; then
    ok "API already running (pid $(cat "$PID_DIR/api.pid"))"
    return
  fi
  log "Starting API on :8000..."
  (
    # shellcheck disable=SC1091
    source "$ROOT/apps/api/.venv/bin/activate"
    set -a
    # shellcheck disable=SC1090
    source "$COMPOSE_ENV"
    set +a
    export PYTHONPATH="$ROOT/apps/api:$ROOT"
    cd "$ROOT/apps/api"
    nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload \
      >"$LOG_DIR/api.log" 2>&1 &
    echo $! >"$PID_DIR/api.pid"
  )
}

start_web_native() {
  if [[ -f "$PID_DIR/web.pid" ]] && kill -0 "$(cat "$PID_DIR/web.pid")" 2>/dev/null; then
    ok "Web already running (pid $(cat "$PID_DIR/web.pid"))"
    return
  fi
  log "Starting web with npm on :5173..."
  (
    cd "$ROOT/apps/web"
    export VITE_API_URL=http://localhost:8000
    export VITE_APP_NAME="FDE Forge AI"
    nohup npm run dev -- --host 0.0.0.0 --port 5173 >"$LOG_DIR/web.log" 2>&1 &
    echo $! >"$PID_DIR/web.pid"
  )
}

start_worker_native() {
  if [[ -f "$PID_DIR/worker.pid" ]] && kill -0 "$(cat "$PID_DIR/worker.pid")" 2>/dev/null; then
    ok "Celery worker already running (pid $(cat "$PID_DIR/worker.pid"))"
    return
  fi
  if ! have redis-cli || ! redis-cli ping >/dev/null 2>&1; then
    warn "Skipping Celery worker (Redis not available)"
    return
  fi
  log "Starting Celery worker..."
  (
    # shellcheck disable=SC1091
    source "$ROOT/apps/api/.venv/bin/activate"
    set -a
    # shellcheck disable=SC1090
    source "$COMPOSE_ENV"
    set +a
    export PYTHONPATH="$ROOT/apps/api:$ROOT"
    cd "$ROOT/apps/api"
    nohup celery -A app.worker.celery_app worker --loglevel=info --concurrency=2 \
      >"$LOG_DIR/worker.log" 2>&1 &
    echo $! >"$PID_DIR/worker.pid"
  )
}

check_bedrock_hint() {
  if [[ ! -f "$HOME/.aws/credentials" ]] && [[ -z "${AWS_ACCESS_KEY_ID:-}" ]] && [[ ! -d "$HOME/.aws" ]]; then
    warn "No AWS credentials found — Bedrock AI needs ~/.aws (you said TCS Mac is already configured)."
  else
    ok "AWS credentials present — Bedrock is the only AI provider on this Mac"
  fi
}

run_native() {
  log "Mode: NATIVE (TCS Mac — no Docker; Homebrew NOT required)"
  if (( HAS_BREW == 1 )); then
    ok "Homebrew detected (optional only — will use if needed)"
  else
    ok "No Homebrew — using system npm / Node / Python / Postgres"
  fi

  have node && have npm || die "Need both node and npm on PATH"
  have python3 || have python3.12 || die "Need python3 on PATH"
  have psql || die "Need psql on PATH (company Postgres)"

  write_native_env
  setup_postgres_native
  setup_redis_native
  setup_minio_native
  setup_python_native
  setup_node_native
  migrate_and_seed_native
  check_bedrock_hint

  if [[ "${SKIP_START:-0}" == "1" ]]; then
    ok "Install complete (SKIP_START=1). Start later with: FORCE_MODE=native ./setup.sh"
    return
  fi

  start_api_native
  start_worker_native
  start_web_native
  wait_http "http://127.0.0.1:8000/api/v1/health" "API" 90 || true
  wait_http "http://127.0.0.1:5173" "Web" 90 || true

  echo ""
  ok "FDE Forge AI is running (native / no Homebrew)"
  echo "  Web UI:   http://localhost:5173"
  echo "  API docs: http://localhost:8000/docs"
  echo "  Login:    Saurabh / admin123 / org acme-health"
  echo "  Logs:     $LOG_DIR"
  echo "  Stop:     ./scripts/stop.sh"
  echo "  AI:       Bedrock only — docs/BEDROCK.md"
}

ensure_docker_env_ec2() {
  if [[ ! -f "$COMPOSE_ENV" ]]; then
    cp "$ROOT/.env.example" "$COMPOSE_ENV"
    ok "Created .env from .env.example"
  fi
  for kv in \
    "BEDROCK_ENABLED=true" \
    "AI_DEFAULT_PROVIDER=bedrock" \
    "DEFAULT_LLM_PROVIDER=bedrock" \
    "ENABLED_LLM_PROVIDERS=bedrock" \
    "AWS_REGION=us-east-1" \
    "BEDROCK_MODEL_ID=us.anthropic.claude-sonnet-4-5-20250929-v1:0"; do
    key="${kv%%=*}"
    if grep -q "^${key}=" "$COMPOSE_ENV" 2>/dev/null; then
      sed -i.bak "s|^${key}=.*|${kv}|" "$COMPOSE_ENV" 2>/dev/null \
        || sed -i '' "s|^${key}=.*|${kv}|" "$COMPOSE_ENV"
    else
      echo "$kv" >>"$COMPOSE_ENV"
    fi
  done
  rm -f "$COMPOSE_ENV.bak" 2>/dev/null || true
  ok "EC2/Docker .env: Bedrock only (use instance IAM role — no AWS keys in .env)"
}

run_docker() {
  log "Mode: DOCKER (AWS EC2 / machines with Docker)"
  have docker || die "Docker not found"
  docker compose version >/dev/null 2>&1 || die "docker compose plugin required"
  ensure_docker_env_ec2

  local worker_replicas="${WORKER_REPLICAS:-2}"
  log "Building and starting stack (worker replicas=${worker_replicas})..."
  docker compose up --build -d --scale "worker=${worker_replicas}"

  log "Waiting for API health..."
  wait_http "http://127.0.0.1:8000/api/v1/health" "API" 120 || true
  wait_http "http://127.0.0.1:5173" "Web" 60 || true

  echo ""
  ok "FDE Forge AI is running (Docker)"
  echo "  Web UI:   http://localhost:5173"
  echo "  API docs: http://localhost:8000/docs"
  echo "  Login:    Saurabh / admin123 / org acme-health"
  echo "  Workers:  ${worker_replicas} Celery replicas"
  echo ""
  echo "Scale further on EC2:"
  echo "  WORKER_REPLICAS=4 ./setup.sh"
  echo "  docker compose up -d --scale worker=4"
  echo "  docker compose ps"
  echo "  docker compose logs -f api"
}

# --- main ---
MODE="$(detect_mode)"
log "FDE Forge AI setup — detected mode: $MODE"
log "Repo: $ROOT"

case "$MODE" in
  native) run_native ;;
  docker) run_docker ;;
  *) die "Unknown mode: $MODE" ;;
esac
