#!/usr/bin/env bash
# FDE Forge AI — one-command setup + start
#
# TCS Mac (no Docker): Homebrew Postgres/Redis/MinIO + native API/web, Bedrock on
# AWS EC2 (Docker):    docker compose up --build -d
#
# Usage (from repo root fde-forge-ai/):
#   chmod +x setup.sh
#   ./setup.sh
#
# Optional:
#   FORCE_MODE=native ./setup.sh     # force Homebrew path
#   FORCE_MODE=docker ./setup.sh     # force Docker path
#   WORKER_REPLICAS=4 ./setup.sh     # EC2 Celery scale (default 2)
#   SKIP_START=1 ./setup.sh          # install only
#   ./scripts/stop.sh                # stop native processes

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

RUN_DIR="$ROOT/.run"
LOG_DIR="$RUN_DIR/logs"
PID_DIR="$RUN_DIR/pids"
NATIVE_ENV="$ROOT/.env.native"
COMPOSE_ENV="$ROOT/.env"

mkdir -p "$LOG_DIR" "$PID_DIR"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${BLUE}==>${NC} $*"; }
ok()   { echo -e "${GREEN}✔${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }
die()  { echo -e "${RED}✖${NC} $*"; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

detect_mode() {
  if [[ "${FORCE_MODE:-}" == "native" || "${FORCE_MODE:-}" == "docker" ]]; then
    echo "$FORCE_MODE"
    return
  fi
  if have docker && docker info >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    echo "docker"
  else
    echo "native"
  fi
}

wait_http() {
  local url="$1" name="$2" tries="${3:-60}"
  local i=0
  while (( i < tries )); do
    if curl -sf "$url" >/dev/null 2>&1; then
      ok "$name is up ($url)"
      return 0
    fi
    sleep 1
    ((i++)) || true
  done
  warn "$name not responding yet at $url (check $LOG_DIR)"
  return 1
}

ensure_brew() {
  if have brew; then
    ok "Homebrew present"
    return
  fi
  die "Homebrew is required on TCS Mac (no Docker). Install from https://brew.sh then re-run ./setup.sh"
}

brew_install() {
  local pkg="$1"
  if brew list --versions "$pkg" >/dev/null 2>&1 || brew list --cask --versions "$pkg" >/dev/null 2>&1; then
    ok "$pkg already installed"
  else
    log "Installing $pkg..."
    brew install "$pkg"
  fi
}

write_native_env() {
  # Keep existing native .env so secret keys don't rotate on every re-run
  if [[ -f "$COMPOSE_ENV" ]] && grep -q '127.0.0.1:5432/fde_forge' "$COMPOSE_ENV" 2>/dev/null \
    && grep -q '^BEDROCK_ENABLED=true' "$COMPOSE_ENV" 2>/dev/null; then
    ok "Using existing .env (native + Bedrock)"
    return
  fi

  log "Writing native .env (localhost services + Bedrock only)..."
  local secret csrf existing_openai=""
  if [[ -f "$COMPOSE_ENV" ]]; then
    secret="$(grep -E '^SECRET_KEY=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- || true)"
    csrf="$(grep -E '^CSRF_SECRET=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- || true)"
    existing_openai="$(grep -E '^OPENAI_API_KEY=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- || true)"
  fi
  [[ -n "${secret:-}" ]] || secret="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"
  [[ -n "${csrf:-}" ]] || csrf="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"

  cat > "$NATIVE_ENV" <<EOF
# Auto-generated by setup.sh for TCS Mac (native / no Docker)
# AI: Bedrock only — configure ~/.aws (aws configure), region us-east-1
APP_ENV=development
APP_NAME=FDE Forge AI
APP_TAGLINE=Transform AI Engineers into Customer-Ready Forward Deployed Engineers.
APP_URL=http://localhost:5173
API_URL=http://localhost:8000
API_PREFIX=/api/v1
SECRET_KEY=${secret}
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
CSRF_SECRET=${csrf}
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
COOKIE_SECURE=false
COOKIE_SAMESITE=lax

DATABASE_URL=postgresql+asyncpg://fde:fde_secret@127.0.0.1:5432/fde_forge
DATABASE_URL_SYNC=postgresql://fde:fde_secret@127.0.0.1:5432/fde_forge

REDIS_URL=redis://127.0.0.1:6379/0
CELERY_BROKER_URL=redis://127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/1

S3_ENDPOINT=http://127.0.0.1:9000
S3_PUBLIC_ENDPOINT=http://127.0.0.1:9000
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=minioadmin
S3_BUCKET=fde-forge
S3_REGION=us-east-1
S3_USE_SSL=false

OPENAI_API_KEY=${existing_openai}
OPENAI_MODEL=gpt-4o-mini
OPENAI_EMBEDDING_MODEL=text-embedding-3-small
AI_DEFAULT_PROVIDER=bedrock
DEFAULT_LLM_PROVIDER=bedrock
ENABLED_LLM_PROVIDERS=bedrock
AI_DEFAULT_MODEL=gpt-4o-mini
AI_MAX_RETRIES=3
AI_REQUEST_TIMEOUT_SECONDS=180
AI_DAILY_ORG_BUDGET=50.00
AI_FALLBACK_MODEL=

BEDROCK_ENABLED=true
AWS_REGION=us-east-1
BEDROCK_MODEL_ID=us.anthropic.claude-sonnet-4-5-20250929-v1:0
BEDROCK_EMBEDDING_MODEL_ID=amazon.titan-embed-text-v2:0
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

SMTP_HOST=127.0.0.1
SMTP_PORT=1025
SMTP_FROM_EMAIL=noreply@fdeforge.example.com
SMTP_USE_TLS=false

LOG_LEVEL=INFO
SEED_ADMIN_EMAIL=saurabh@fdeforge.example.com
SEED_ADMIN_PASSWORD=admin123
SEED_LEARNER_PASSWORD=ChangeMeLearner123!
EOF

  cp "$NATIVE_ENV" "$COMPOSE_ENV"
  ok "Wrote $COMPOSE_ENV (Bedrock only for TCS Mac)"
}

setup_postgres_native() {
  brew_install postgresql@16
  brew_install pgvector || warn "pgvector formula missing — vector extension may fail; install later if needed"

  # Prefer brew postgresql@16 path
  local pg_prefix
  pg_prefix="$(brew --prefix postgresql@16 2>/dev/null || true)"
  if [[ -n "$pg_prefix" && -d "$pg_prefix/bin" ]]; then
    export PATH="$pg_prefix/bin:$PATH"
  fi

  if ! brew services list 2>/dev/null | grep -q "postgresql@16.*started"; then
    log "Starting postgresql@16..."
    brew services start postgresql@16 || brew services restart postgresql@16
  else
    ok "postgresql@16 already running"
  fi

  sleep 2
  # Create role/db (idempotent)
  if ! psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='fde'" 2>/dev/null | grep -q 1; then
    log "Creating Postgres role fde..."
    createuser -s fde 2>/dev/null || true
    psql postgres -c "ALTER USER fde WITH PASSWORD 'fde_secret';" 2>/dev/null || \
      psql postgres -c "CREATE USER fde WITH PASSWORD 'fde_secret' SUPERUSER;" 
  else
    psql postgres -c "ALTER USER fde WITH PASSWORD 'fde_secret';" >/dev/null 2>&1 || true
  fi

  if ! psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname='fde_forge'" 2>/dev/null | grep -q 1; then
    createdb -O fde fde_forge
  fi

  PGPASSWORD=fde_secret psql -h 127.0.0.1 -U fde -d fde_forge -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' >/dev/null
  PGPASSWORD=fde_secret psql -h 127.0.0.1 -U fde -d fde_forge -c 'CREATE EXTENSION IF NOT EXISTS vector;' >/dev/null 2>&1 \
    || warn "vector extension failed — install pgvector for your Postgres, then re-run"
  PGPASSWORD=fde_secret psql -h 127.0.0.1 -U fde -d fde_forge -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' >/dev/null
  ok "Postgres ready (fde_forge @ 127.0.0.1:5432)"
}

setup_redis_native() {
  brew_install redis
  if ! brew services list 2>/dev/null | grep -q "redis.*started"; then
    brew services start redis
  fi
  ok "Redis ready (6379)"
}

setup_minio_native() {
  if ! have minio; then
    log "Installing MinIO..."
    brew install minio/stable/minio || brew install minio
  fi
  if ! have mc; then
    brew install minio/stable/mc || brew install minio-mc || warn "mc not installed — will create bucket via AWS CLI if available"
  fi

  mkdir -p "$RUN_DIR/minio-data"
  export MINIO_ROOT_USER=minioadmin MINIO_ROOT_PASSWORD=minioadmin
  if [[ -f "$PID_DIR/minio.pid" ]] && kill -0 "$(cat "$PID_DIR/minio.pid")" 2>/dev/null; then
    ok "MinIO already running"
  else
    log "Starting MinIO..."
    nohup env MINIO_ROOT_USER=minioadmin MINIO_ROOT_PASSWORD=minioadmin \
      minio server "$RUN_DIR/minio-data" --address ":9000" --console-address ":9001" \
      >"$LOG_DIR/minio.log" 2>&1 &
    echo $! >"$PID_DIR/minio.pid"
    sleep 2
  fi

  # Ensure bucket
  if have mc; then
    mc alias set local http://127.0.0.1:9000 minioadmin minioadmin >/dev/null 2>&1 || true
    mc mb -p local/fde-forge >/dev/null 2>&1 || true
  elif have aws; then
    AWS_ACCESS_KEY_ID=minioadmin AWS_SECRET_ACCESS_KEY=minioadmin \
      aws --endpoint-url http://127.0.0.1:9000 s3 mb s3://fde-forge >/dev/null 2>&1 || true
  fi
  ok "MinIO ready (http://127.0.0.1:9000)"
}

setup_python_native() {
  brew_install python@3.12 || brew_install python3
  local py
  py="$(command -v python3.12 || command -v python3)"
  [[ -x "$py" ]] || die "Python 3.12+ required"
  log "Python: $($py --version)"

  if [[ ! -d "$ROOT/apps/api/.venv" ]]; then
    "$py" -m venv "$ROOT/apps/api/.venv"
  fi
  # shellcheck disable=SC1091
  source "$ROOT/apps/api/.venv/bin/activate"
  pip install -q --upgrade pip
  log "Installing API package..."
  pip install -q -e "$ROOT/apps/api[dev]"
  ok "Python venv ready"
}

setup_node_native() {
  if ! have node; then
    brew_install node
  fi
  log "Node: $(node --version) / npm $(npm --version)"
  log "Installing web dependencies..."
  (cd "$ROOT/apps/web" && npm install)
  ok "Web dependencies ready"
}

migrate_and_seed_native() {
  # shellcheck disable=SC1091
  source "$ROOT/apps/api/.venv/bin/activate"
  export PYTHONPATH="$ROOT/apps/api:$ROOT:${PYTHONPATH:-}"
  # Load env for alembic/seed
  set -a
  # shellcheck disable=SC1090
  source "$COMPOSE_ENV"
  set +a

  log "Running Alembic migrations..."
  (cd "$ROOT/apps/api" && alembic -c alembic.ini upgrade head)
  log "Seeding demo data..."
  (cd "$ROOT" && PYTHONPATH="$ROOT/apps/api:$ROOT" python -m scripts.seed) || warn "Seed had warnings (often OK if already seeded)"
  ok "DB migrated + seeded"
}

start_api_native() {
  if [[ -f "$PID_DIR/api.pid" ]] && kill -0 "$(cat "$PID_DIR/api.pid")" 2>/dev/null; then
    ok "API already running (pid $(cat "$PID_DIR/api.pid"))"
    return
  fi
  log "Starting API on :8000..."
  (
    # shellcheck disable=SC1091
    source "$ROOT/apps/api/.venv/bin/activate"
    set -a
    # shellcheck disable=SC1090
    source "$COMPOSE_ENV"
    set +a
    export PYTHONPATH="$ROOT/apps/api:$ROOT"
    cd "$ROOT/apps/api"
    nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload \
      >"$LOG_DIR/api.log" 2>&1 &
    echo $! >"$PID_DIR/api.pid"
  )
}

start_web_native() {
  if [[ -f "$PID_DIR/web.pid" ]] && kill -0 "$(cat "$PID_DIR/web.pid")" 2>/dev/null; then
    ok "Web already running (pid $(cat "$PID_DIR/web.pid"))"
    return
  fi
  log "Starting web on :5173..."
  (
    cd "$ROOT/apps/web"
    export VITE_API_URL=http://localhost:8000
    export VITE_APP_NAME="FDE Forge AI"
    nohup npm run dev -- --host 0.0.0.0 --port 5173 >"$LOG_DIR/web.log" 2>&1 &
    echo $! >"$PID_DIR/web.pid"
  )
}

start_worker_native() {
  if [[ -f "$PID_DIR/worker.pid" ]] && kill -0 "$(cat "$PID_DIR/worker.pid")" 2>/dev/null; then
    ok "Celery worker already running (pid $(cat "$PID_DIR/worker.pid"))"
    return
  fi
  log "Starting Celery worker..."
  (
    # shellcheck disable=SC1091
    source "$ROOT/apps/api/.venv/bin/activate"
    set -a
    # shellcheck disable=SC1090
    source "$COMPOSE_ENV"
    set +a
    export PYTHONPATH="$ROOT/apps/api:$ROOT"
    cd "$ROOT/apps/api"
    nohup celery -A app.worker.celery_app worker --loglevel=info --concurrency=2 \
      >"$LOG_DIR/worker.log" 2>&1 &
    echo $! >"$PID_DIR/worker.pid"
  )
}

check_bedrock_hint() {
  if [[ ! -f "$HOME/.aws/credentials" ]] && [[ -z "${AWS_ACCESS_KEY_ID:-}" ]]; then
    warn "No AWS credentials found — configure Bedrock before AI features work:"
    warn "  aws configure   # region us-east-1, keys with bedrock:InvokeModel"
    warn "App will still start; AI calls fail until Bedrock credentials work."
  else
    ok "AWS credentials present — Bedrock is the only AI provider on this Mac"
  fi
}

run_native() {
  log "Mode: NATIVE (TCS Mac — Homebrew, no Docker)"
  ensure_brew
  write_native_env
  setup_postgres_native
  setup_redis_native
  setup_minio_native
  setup_python_native
  setup_node_native
  migrate_and_seed_native
  check_bedrock_hint

  if [[ "${SKIP_START:-0}" == "1" ]]; then
    ok "Install complete (SKIP_START=1). Start later with: ./setup.sh"
    return
  fi

  start_api_native
  start_worker_native
  start_web_native
  wait_http "http://127.0.0.1:8000/api/v1/health" "API" 90 || true
  wait_http "http://127.0.0.1:5173" "Web" 90 || true

  echo ""
  ok "FDE Forge AI is running (native)"
  echo "  Web UI:   http://localhost:5173"
  echo "  API docs: http://localhost:8000/docs"
  echo "  MinIO:    http://localhost:9001  (minioadmin / minioadmin)"
  echo "  Login:    Saurabh / admin123 / org acme-health"
  echo "  Logs:     $LOG_DIR"
  echo "  Stop:     ./scripts/stop.sh"
  echo "  AI:       Bedrock only — docs/BEDROCK.md"
}

ensure_docker_env_ec2() {
  if [[ ! -f "$COMPOSE_ENV" ]]; then
    cp "$ROOT/.env.example" "$COMPOSE_ENV"
    ok "Created .env from .env.example"
  fi
  # Prefer Bedrock on EC2 (IAM role)
  for kv in \
    "BEDROCK_ENABLED=true" \
    "AI_DEFAULT_PROVIDER=bedrock" \
    "DEFAULT_LLM_PROVIDER=bedrock" \
    "ENABLED_LLM_PROVIDERS=bedrock" \
    "AWS_REGION=us-east-1" \
    "BEDROCK_MODEL_ID=us.anthropic.claude-sonnet-4-5-20250929-v1:0"; do
    key="${kv%%=*}"
    if grep -q "^${key}=" "$COMPOSE_ENV" 2>/dev/null; then
      sed -i.bak "s|^${key}=.*|${kv}|" "$COMPOSE_ENV" 2>/dev/null \
        || sed -i '' "s|^${key}=.*|${kv}|" "$COMPOSE_ENV"
    else
      echo "$kv" >>"$COMPOSE_ENV"
    fi
  done
  rm -f "$COMPOSE_ENV.bak" 2>/dev/null || true
  ok "EC2/Docker .env: Bedrock only (use instance IAM role — no AWS keys in .env)"
}

run_docker() {
  log "Mode: DOCKER (AWS EC2 / machines with Docker)"
  have docker || die "Docker not found"
  docker compose version >/dev/null 2>&1 || die "docker compose plugin required"
  ensure_docker_env_ec2

  local worker_replicas="${WORKER_REPLICAS:-2}"
  log "Building and starting stack (worker replicas=${worker_replicas})..."
  docker compose up --build -d --scale "worker=${worker_replicas}"

  log "Waiting for API health..."
  wait_http "http://127.0.0.1:8000/api/v1/health" "API" 120 || true
  wait_http "http://127.0.0.1:5173" "Web" 60 || true

  echo ""
  ok "FDE Forge AI is running (Docker)"
  echo "  Web UI:   http://localhost:5173"
  echo "  API docs: http://localhost:8000/docs"
  echo "  Login:    Saurabh / admin123 / org acme-health"
  echo "  Workers:  ${worker_replicas} Celery replicas"
  echo ""
  echo "Scale further on EC2:"
  echo "  WORKER_REPLICAS=4 ./setup.sh"
  echo "  docker compose up -d --scale worker=4"
  echo "  docker compose ps"
  echo "  docker compose logs -f api"
}

# --- main ---
MODE="$(detect_mode)"
log "FDE Forge AI setup — detected mode: $MODE"
log "Repo: $ROOT"

case "$MODE" in
  native) run_native ;;
  docker) run_docker ;;
  *) die "Unknown mode: $MODE" ;;
esac
