#!/usr/bin/env bash
# FDE Forge AI — setup without Docker (TCS Mac / Bedrock + SQLite)
# Inspired by Knowledge Fabric setup_without_docker.sh
#
# TCS Mac (default when no Docker):
#   Python venv + npm + SQLite file DB + local uploads + Bedrock (~/.aws)
#   No Homebrew, Postgres, Redis, MinIO, or Docker required.
#
# AWS EC2 (when Docker is available):
#   docker compose up --build -d --scale worker=2
#
# Usage:
#   chmod +x setup.sh scripts/stop.sh
#   ./setup.sh
#   FORCE_MODE=native ./setup.sh
#   FORCE_MODE=docker ./setup.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

RUN_DIR="${FDE_RUN_DIR:-$HOME/.fde-forge-ai}"
LOG_DIR="$RUN_DIR/logs"
PID_DIR="$RUN_DIR/pids"
DB_FILE="$RUN_DIR/fde_forge.db"
UPLOAD_DIR="$RUN_DIR/uploads"
COMPOSE_ENV="$ROOT/.env"

mkdir -p "$LOG_DIR" "$PID_DIR" "$UPLOAD_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status()  { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

die() { print_error "$1"; exit 1; }

detect_mode() {
  if [[ "${FORCE_MODE:-}" == "native" || "${FORCE_MODE:-}" == "docker" ]]; then
    echo "$FORCE_MODE"
    return
  fi
  if command_exists docker && docker info >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    echo "docker"
  else
    echo "native"
  fi
}

select_python_command() {
  if [[ -n "${PYTHON_BIN:-}" ]] && command_exists "${PYTHON_BIN}"; then
    echo "${PYTHON_BIN}"
    return
  fi
  local candidate version
  for candidate in python3.12 python3.11 python3; do
    if command_exists "$candidate"; then
      version="$("$candidate" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")' 2>/dev/null || true)"
      case "$version" in
        3.12|3.13|3.11) echo "$candidate"; return ;;
      esac
    fi
  done
  echo ""
}

wait_http() {
  local url="$1" name="$2" tries="${3:-60}" i=0
  while (( i < tries )); do
    if curl -sf "$url" >/dev/null 2>&1; then
      print_success "$name is up ($url)"
      return 0
    fi
    sleep 1
    ((i++)) || true
  done
  print_warning "$name not responding yet at $url — check $LOG_DIR"
  return 1
}

write_sqlite_env() {
  print_status "Writing .env for TCS Mac (SQLite + local storage + Bedrock)..."
  local secret csrf
  # Spaces in paths break bash `source` and SQLite URLs — keep DB under $HOME
  local db_url_path upload_quoted
  db_url_path="${DB_FILE// /%20}"
  upload_quoted="${UPLOAD_DIR}"

  if [[ -f "$COMPOSE_ENV" ]] && grep -q 'sqlite' "$COMPOSE_ENV" 2>/dev/null \
    && grep -q '^BEDROCK_ENABLED=true' "$COMPOSE_ENV" 2>/dev/null \
    && grep -q 'fde_forge.db' "$COMPOSE_ENV" 2>/dev/null \
    && ! grep -q 'FDE Forge AI' "$COMPOSE_ENV" 2>/dev/null; then
    print_success "Using existing SQLite .env"
    return
  fi

  if [[ -f "$COMPOSE_ENV" ]]; then
    secret="$(grep -E '^SECRET_KEY=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true)"
    csrf="$(grep -E '^CSRF_SECRET=' "$COMPOSE_ENV" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true)"
  fi
  [[ -n "${secret:-}" ]] || secret="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"
  [[ -n "${csrf:-}" ]] || csrf="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"

  cat > "$COMPOSE_ENV" <<EOF
# Auto-generated by setup.sh — TCS Mac native (SQLite, no Docker)
APP_ENV=development
APP_NAME="FDE Forge AI"
APP_TAGLINE="Transform AI Engineers into Customer-Ready Forward Deployed Engineers."
APP_URL=http://localhost:5173
API_URL=http://localhost:8000
API_PREFIX=/api/v1
SECRET_KEY=${secret}
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
CSRF_SECRET=${csrf}
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
COOKIE_SECURE=false
COOKIE_SAMESITE=lax

DATABASE_URL=sqlite+aiosqlite:///${db_url_path}
DATABASE_URL_SYNC=sqlite:///${db_url_path}

REDIS_URL=redis://127.0.0.1:6379/0
CELERY_BROKER_URL=redis://127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/1

STORAGE_BACKEND=local
LOCAL_STORAGE_PATH="${upload_quoted}"

S3_ENDPOINT=http://127.0.0.1:9000
S3_PUBLIC_ENDPOINT=http://127.0.0.1:9000
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=minioadmin
S3_BUCKET=fde-forge
S3_REGION=us-east-1
S3_USE_SSL=false

OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini
OPENAI_EMBEDDING_MODEL=text-embedding-3-small
AI_DEFAULT_PROVIDER=bedrock
DEFAULT_LLM_PROVIDER=bedrock
ENABLED_LLM_PROVIDERS=bedrock
AI_DEFAULT_MODEL=gpt-4o-mini
AI_MAX_RETRIES=3
AI_REQUEST_TIMEOUT_SECONDS=180
AI_DAILY_ORG_BUDGET=50.00
AI_FALLBACK_MODEL=

BEDROCK_ENABLED=true
AWS_REGION=us-east-1
BEDROCK_MODEL_ID=us.anthropic.claude-sonnet-4-5-20250929-v1:0
BEDROCK_EMBEDDING_MODEL_ID=amazon.titan-embed-text-v2:0
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

SMTP_HOST=127.0.0.1
SMTP_PORT=1025
SMTP_FROM_EMAIL=noreply@fdeforge.example.com
SMTP_USE_TLS=false

LOG_LEVEL=INFO
SEED_ADMIN_EMAIL=saurabh@fdeforge.example.com
SEED_ADMIN_PASSWORD=admin123
SEED_LEARNER_PASSWORD=ChangeMeLearner123!
EOF
  print_success "Environment file created (.env — SQLite + Bedrock)"
  print_status "SQLite DB: $DB_FILE"
}

install_python_deps() {
  print_status "Installing Python dependencies..."
  local PYTHON_CMD
  PYTHON_CMD="$(select_python_command)"
  if [[ -z "$PYTHON_CMD" ]]; then
    die "Need Python 3.11+ (3.12 recommended). Set PYTHON_BIN=python3.12 if needed."
  fi
  print_success "Using $($PYTHON_CMD --version) via '${PYTHON_CMD}'"

  if [[ ! -d "$ROOT/apps/api/.venv" ]]; then
    print_status "Creating Python virtual environment..."
    "$PYTHON_CMD" -m venv "$ROOT/apps/api/.venv"
    print_success "Virtual environment created"
  else
    print_status "Virtual environment already exists"
  fi

  # shellcheck disable=SC1091
  source "$ROOT/apps/api/.venv/bin/activate"
  pip install --upgrade pip
  print_status "Installing API package..."
  pip install -e "$ROOT/apps/api[dev]"
  print_success "Python dependencies installed"
}

install_node_deps() {
  print_status "Installing Node.js dependencies..."
  command_exists node || die "Node.js is not installed. Install Node 18+ (npm comes with it)."
  command_exists npm || die "npm is not installed / not on PATH."

  local node_version
  node_version="$(node -v | cut -d'v' -f2)"
  print_success "Node.js version $node_version / npm $(npm --version)"

  (cd "$ROOT/apps/web" && npm install)
  print_success "Node.js dependencies installed"
}

init_sqlite_and_seed() {
  print_status "Initializing SQLite schema + demo seed..."
  # shellcheck disable=SC1091
  source "$ROOT/apps/api/.venv/bin/activate"
  set -a
  # shellcheck disable=SC1090
  source "$COMPOSE_ENV"
  set +a
  export PYTHONPATH="$ROOT/apps/api:$ROOT"

  # Clear settings cache by using a fresh process
  (cd "$ROOT" && python -m scripts.init_sqlite)
  (cd "$ROOT" && python -m scripts.seed) || print_warning "Seed had warnings (OK if already seeded)"
  print_success "SQLite DB ready: $DB_FILE"
}

check_ports() {
  print_status "Checking if required ports are available..."
  if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    print_warning "Port 8000 is already in use. API may not start properly."
  else
    print_success "Port 8000 is available"
  fi
  if lsof -Pi :5173 -sTCP:LISTEN -t >/dev/null 2>&1; then
    print_warning "Port 5173 is already in use. Web may not start properly."
  else
    print_success "Port 5173 is available"
  fi
}

check_bedrock() {
  if [[ -f "$HOME/.aws/credentials" ]] || [[ -d "$HOME/.aws" ]]; then
    print_success "AWS credentials found — Bedrock will use ~/.aws"
  else
    print_warning "No ~/.aws found — AI features need Bedrock credentials (aws configure)."
  fi
}

create_start_scripts() {
  print_status "Creating start scripts..."

  cat > "$ROOT/start_backend.sh" <<EOF
#!/bin/bash
cd "$ROOT"
set -a
source "$COMPOSE_ENV"
set +a
source "$ROOT/apps/api/.venv/bin/activate"
export PYTHONPATH="$ROOT/apps/api:$ROOT"
cd "$ROOT/apps/api"
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
EOF

  cat > "$ROOT/start_frontend.sh" <<EOF
#!/bin/bash
cd "$ROOT/apps/web"
export VITE_API_URL=http://localhost:8000
export VITE_APP_NAME="FDE Forge AI"
npm run dev -- --host 0.0.0.0 --port 5173
EOF

  cat > "$ROOT/start_all.sh" <<EOF
#!/bin/bash
set -e
cd "$ROOT"
echo "Starting FDE Forge AI (SQLite / no Docker)..."

set -a
source "$COMPOSE_ENV"
set +a
source "$ROOT/apps/api/.venv/bin/activate"
export PYTHONPATH="$ROOT/apps/api:$ROOT"

cd "$ROOT/apps/api"
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=\$!

sleep 2
cd "$ROOT/apps/web"
export VITE_API_URL=http://localhost:8000
export VITE_APP_NAME="FDE Forge AI"
npm run dev -- --host 0.0.0.0 --port 5173 &
FRONTEND_PID=\$!

echo "Backend PID: \$BACKEND_PID"
echo "Frontend PID: \$FRONTEND_PID"
echo "Frontend: http://localhost:5173"
echo "API docs: http://localhost:8000/docs"
echo "Login: Saurabh / admin123 / org acme-health"
echo "Press Ctrl+C to stop"
trap 'kill \$BACKEND_PID \$FRONTEND_PID 2>/dev/null' EXIT
wait
EOF

  chmod +x "$ROOT/start_backend.sh" "$ROOT/start_frontend.sh" "$ROOT/start_all.sh"
  print_success "Start scripts created (start_all.sh / start_backend.sh / start_frontend.sh)"
}

start_services_background() {
  if [[ "${SKIP_START:-0}" == "1" ]]; then
    print_success "Install complete (SKIP_START=1). Run ./start_all.sh when ready."
    return
  fi

  print_status "Starting API + web in background..."
  (
    set -a
    # shellcheck disable=SC1090
    source "$COMPOSE_ENV"
    set +a
    # shellcheck disable=SC1091
    source "$ROOT/apps/api/.venv/bin/activate"
    export PYTHONPATH="$ROOT/apps/api:$ROOT"
    cd "$ROOT/apps/api"
    nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload >"$LOG_DIR/api.log" 2>&1 &
    echo $! >"$PID_DIR/api.pid"
  )
  (
    cd "$ROOT/apps/web"
    export VITE_API_URL=http://localhost:8000
    export VITE_APP_NAME="FDE Forge AI"
    nohup npm run dev -- --host 0.0.0.0 --port 5173 >"$LOG_DIR/web.log" 2>&1 &
    echo $! >"$PID_DIR/web.pid"
  )

  wait_http "http://127.0.0.1:8000/api/v1/health" "API" 90 || true
  wait_http "http://127.0.0.1:5173" "Web" 90 || true
}

show_final_instructions() {
  echo ""
  echo "=========================================="
  echo "FDE Forge AI setup complete (TCS / SQLite)"
  echo "=========================================="
  echo ""
  echo "  Frontend:  http://localhost:5173"
  echo "  API docs:  http://localhost:8000/docs"
  echo "  Login:     Saurabh / admin123 / org acme-health"
  echo "  Database:  $DB_FILE"
  echo "  Uploads:   $UPLOAD_DIR"
  echo "  AI:        Bedrock via ~/.aws"
  echo ""
  echo "  Start later:  ./start_all.sh"
  echo "  Stop:         ./scripts/stop.sh"
  echo "  Logs:         $LOG_DIR"
  echo ""
}

run_native() {
  echo "=========================================="
  echo "FDE Forge AI — Setup Without Docker"
  echo "TCS Mac · SQLite · npm · Bedrock"
  echo "=========================================="
  echo ""

  [[ -f "$ROOT/apps/api/pyproject.toml" && -f "$ROOT/apps/web/package.json" ]] \
    || die "Run this script from the fde-forge-ai repo root"

  write_sqlite_env
  install_python_deps
  install_node_deps
  init_sqlite_and_seed
  check_ports
  check_bedrock
  create_start_scripts
  start_services_background
  show_final_instructions
}

ensure_docker_env_ec2() {
  if [[ ! -f "$COMPOSE_ENV" ]]; then
    cp "$ROOT/.env.example" "$COMPOSE_ENV"
    print_success "Created .env from .env.example"
  fi
  for kv in \
    "BEDROCK_ENABLED=true" \
    "AI_DEFAULT_PROVIDER=bedrock" \
    "DEFAULT_LLM_PROVIDER=bedrock" \
    "ENABLED_LLM_PROVIDERS=bedrock" \
    "STORAGE_BACKEND=s3" \
    "AWS_REGION=us-east-1" \
    "BEDROCK_MODEL_ID=us.anthropic.claude-sonnet-4-5-20250929-v1:0"; do
    key="${kv%%=*}"
    if grep -q "^${key}=" "$COMPOSE_ENV" 2>/dev/null; then
      sed -i.bak "s|^${key}=.*|${kv}|" "$COMPOSE_ENV" 2>/dev/null \
        || sed -i '' "s|^${key}=.*|${kv}|" "$COMPOSE_ENV"
    else
      echo "$kv" >>"$COMPOSE_ENV"
    fi
  done
  rm -f "$COMPOSE_ENV.bak" 2>/dev/null || true
}

run_docker() {
  print_status "Mode: DOCKER (AWS EC2)"
  command_exists docker || die "Docker not found"
  docker compose version >/dev/null 2>&1 || die "docker compose plugin required"
  ensure_docker_env_ec2
  local worker_replicas="${WORKER_REPLICAS:-2}"
  print_status "Building and starting stack (worker replicas=${worker_replicas})..."
  docker compose up --build -d --scale "worker=${worker_replicas}"
  wait_http "http://127.0.0.1:8000/api/v1/health" "API" 120 || true
  wait_http "http://127.0.0.1:5173" "Web" 60 || true
  print_success "Docker stack running — http://localhost:5173"
}

# --- main ---
MODE="$(detect_mode)"
print_status "Detected mode: $MODE"
print_status "Repo: $ROOT"

case "$MODE" in
  native) run_native ;;
  docker) run_docker ;;
  *) die "Unknown mode: $MODE" ;;
esac
